### ISSUE TITLE
通过docker启动成功，但显示未配置签名服务器

### ISSUE THREAD

**Issue by symbolworld** [XZhouQD/unidbg-fetch-qsign#11]
如图：
![code45](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/114469878/30623aac-761b-48b9-9a8d-f93e392df345)
通过docker部署的方法，把qsign启动成功了，但一直显示未配置，不知道哪里出了问题。希望提供一些可能出错的地方。
go-cqhttp的版本是：v1.1.0

**Comment by XZhouQD** [comment]
@symbolworld qsign适配的是安卓和安卓pad协议，8.9.63版本，请切换到Android/Apad

**Comment by symbolworld** [comment]
> @symbolworld qsign适配的是安卓和安卓pad协议，8.9.63版本，请切换到Android/Apad
我试着从device.json文件中的protocol字段中改了协议，从5改成了1，因为1是Android协议。还是显示未配置签名。我有一个地方没看明白，就是：sso 版本必须和协议版本一致。这句话是什么意思？我不了解sso是什么，又怎么确保它们一致呢？望指点一二。

**Comment by XZhouQD** [comment]
切换到安卓协议后，你应该可以在gocq的启动日志里看到使用的协议版本，如 `Android 8.9.63` ，然后，确认你使用了正确的qsign（比如8.9.63就用xzhouqd/qsign:8.9.63），然后，把qsign的运行地址，填到gocq的config里去，如果config里没地方填，可以删掉config让gocq重新生成一份

**Comment by symbolworld** [comment]
> 切换到安卓协议后，你应该可以在gocq的启动日志里看到使用的协议版本，如 `Android 8.9.63` ，然后，确认你使用了正确的qsign（比如8.9.63就用xzhouqd/qsign:8.9.63），然后，把qsign的运行地址，填到gocq的config里去，如果config里没地方填，可以删掉config让gocq重新生成一份

感谢大佬，已成功登录。
重新生成config.yml，然后配置了sign-server这一项就好了。

**Comment by lllrj** [comment]
@symbolworld 请问你的qsign是哪个版本的？我这里参照1.1.0tag下的docker-compose.yml一直报错bash bin/xxx
