### ISSUE TITLE
关于1.1.0go-cqhttp适配1.1.7

### ISSUE THREAD

**Issue by Ch1ldKing** [XZhouQD/unidbg-fetch-qsign#13]
1.1.7版本的unidbg-fetch-qsign的docker版本适配最新版gocq了吗，如果适配了的话在哪里填写android id在哪里填写呢

**Comment by XZhouQD** [comment]
@Ch1ldKing 1.1.7已经是注册模式了，不填android id的，docker镜像启动详见[Dockerhub: xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)
