### ISSUE TITLE
This mutex is not locked

### ISSUE THREAD

**Issue by Yizelove** [XZhouQD/unidbg-fetch-qsign#16]
docker部署的1.1.7版本API运行一会就会返回This mutex is not locked，这是咋回事？
![日志截图](https://img.cdn.tencent-qq.cn/Yize/2023/08/fafb04c0916ef6cf.jpg)

**Comment by XZhouQD** [comment]
需要qsign那边的对应log，另外这个和docker image部署没关系了，去上游发issue或者去协议端问问
