### ISSUE TITLE
如何能够优化内存占用

### ISSUE THREAD

**Issue by TangbohuDianPaoZhang** [XZhouQD/unidbg-fetch-qsign#20]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
我使用的是Azure b1s的云虚拟机，只有1c1g，开启容器以后服务器内存基本就满了，有没有办法能够减少一点容器所占用的内存

**Comment by XZhouQD** [comment]
如果你用的是8.9.63 tag，你可以增加container参数来限制内存但是爆了就得重启容器了。如果是更新的tag比如core-1.1.9，内存占用大概在230MiB这样子，不要开dynarmic选项

**Comment by XZhouQD** [comment]
closed due to inactivity
