### ISSUE TITLE
可否增加或关闭日志显示

### ISSUE THREAD

**Issue by wordgao** [XZhouQD/unidbg-fetch-qsign#21]
可否增加或关闭日志显示，日志虽然能看到一些关键信息去查找bug，但同时也限制了程序的运行效率。
当前日志滚动频率高，严重影响到程序的运行稳定性和效率。

**Comment by XZhouQD** [comment]
这得找上游[fuqiuluo/unidbg-fetch-qsign](https://github.com/fuqiuluo/unidbg-fetch-qsign)问问……我这边只是打镜像的
