### ISSUE TITLE
Docker 长时间运行之后整个容器会卡住

### ISSUE THREAD

**Issue by 9Bakabaka** [XZhouQD/unidbg-fetch-qsign#22]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
如题，群晖docker运行长时间之后整个容器会卡住，gocq提示T.554（？）错误，并且日志也不再更新
![image](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/140469824/861a69ad-495b-4b27-98a7-2c7c54a5da45)
如图，在10:34分之后日志就不再更新了，直到13:18左右我重启容器才继续更新日志

**Comment by XZhouQD** [comment]
镜像版本？

**Comment by 9Bakabaka** [comment]
core-1.1.9，问题解决了，内存溢出了

Xiaowei Zhou ***@***.***> 於 2023年10月6日 週五 下午6:56 寫道：
