### ISSUE TITLE
使用decker部署无法刷新token

### ISSUE THREAD

**Issue by SolitaryJune** [XZhouQD/unidbg-fetch-qsign#23]
http://host:port/request_token?uin=[QQ]
无法刷新token
docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63
这个部署刷新没有返回值

**Comment by XZhouQD** [comment]
刷token好像是高版本内容？建议切换到core-1.1.9
