### ISSUE TITLE
大佬，能不能更换另一个上游的协议库呢，以及解决下刷新token错误的问题呢

### ISSUE THREAD

**Issue by shange1993** [XZhouQD/unidbg-fetch-qsign#26]
https://github.com/touchscale/Qsign  能不能更到这个协议库里的内容呢，fuqiuluo大佬的协议库貌似不更新了

**Comment by XZhouQD** [comment]
我去看了下，代码是没变的，协议库其实你可以自己下载下来mount进去然后指定path运行的啦，core版本的意义就是这个，协议库可以自己mount来换的
