### ISSUE TITLE
1.1.4+8.9.68获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

### ISSUE THREAD

**Issue by HadalFauna** [XZhouQD/unidbg-fetch-qsign#3]
如题，拉取1.1.4，直接使用docker run -d --restart=always --name qsign -p 12000:8080 -e BASE_PATH=/srv/qsign/qsign/txlib/8.9.68 xzhouqd/qsign:core-1.1.4在amd64ubuntu上部署，未更改配置

搭建后访问api网址显示
{
    "code": 0,
    "msg": "IAA 云天明 章北海",
    "data": {
        "version": "1.1.4",
        "protocol": {
            "qua": "V1_AND_SQ_8.9.68_4218_HDBM_T",
            "version": "8.9.68",
            "code": "4218"
        }
    }
}

但是尝试登录时显示[WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

**Comment by XZhouQD** [comment]
go-cqhttp? 是否使用了最新的actions构建版本？正式版是不可以的

**Comment by HadalFauna** [comment]
> go-cqhttp? 是否使用了最新的actions构建版本？正式版是不可以的

嘶，确实是Release v1.1.0的go-cqhttp，那我继续用1.1.0的qsign苟着了

**Comment by XZhouQD** [comment]
可以尝试使用1.1.5的镜像，映射config.json进去打开autoregister再尝试一下，release v1.1.0配1.1.5+autoregister从理论上是可行的，如果不行，就先用1.1.0吧

**Comment by happy-bear-x** [comment]
> 可以尝试使用1.1.5的镜像，映射config.json进去打开autoregister再尝试一下，release v1.1.0配1.1.5+autoregister从理论上是可行的，如果不行，就先用1.1.0吧
试了下，协议63，1.1.5+autoregister依旧有此问题。
