### ISSUE TITLE
不需要android_id了么

### ISSUE THREAD

**Issue by Mengzx88** [XZhouQD/unidbg-fetch-qsign#5]
最新版本 1.1.5的不用android_id了吗

**Comment by aohanhongzhi** [comment]
为啥我docker直接启动还是需要android_id，android_id是个啥，我需要咋配置？
![image](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/37319319/50f9d3c4-700d-4198-9625-6f87cf48f104)

**Comment by XZhouQD** [comment]
@Mengzx88 1.1.5确实不需要手动传入了，注册机制了，使用/register api

**Comment by XZhouQD** [comment]
@aohanhongzhi android_id可以从你的device.json获取，传入方式例如：`docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63`，是给container传环境变量的方式传入，详见[Dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)

**Comment by lllrj** [comment]
> @aohanhongzhi android_id可以从你的device.json获取，传入方式例如：`docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63`，是给container传环境变量的方式传入，详见[Dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)

大佬你好，我运行你的命令行企图启动qsign服务，但是报错
![image](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/87311200/fb3e23f8-0659-43bf-8cb2-ca015bb328b7)
找不到解决思路，外部有java

**Comment by aohanhongzhi** [comment]
> > @aohanhongzhi android_id可以从你的device.json获取，传入方式例如：`docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63`，是给container传环境变量的方式传入，详见[Dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)
> 
> 大佬你好，我运行你的命令行企图启动qsign服务，但是报错 ![image](https://user-images.githubusercontent.com/87311200/274635894-fb3e23f8-0659-43bf-8cb2-ca015bb328b7.png) 找不到解决思路，外部有java

外部java与docker容器里完全没有关系，你检查下docker里面的java是否正常。

**Comment by lllrj** [comment]
> > > @aohanhongzhi android_id可以从你的device.json获取，传入方式例如：`docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63`，是给container传环境变量的方式传入，详见[Dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)
> > 
> > 
> > 大佬你好，我运行你的命令行企图启动qsign服务，但是报错 ![image](https://user-images.githubusercontent.com/87311200/274635894-fb3e23f8-0659-43bf-8cb2-ca015bb328b7.png) 找不到解决思路，外部有java
> 
> 外部java与docker容器里完全没有关系，你检查下docker里面的java是否正常。

然而问题是容器报这个错，会是restarting状态，我无法进去检查里面的java情况，而且我们用的同一命令，为啥我会出现这个问题呢

**Comment by XZhouQD** [comment]
> > > > @aohanhongzhi android_id可以从你的device.json获取，传入方式例如：`docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63`，是给container传环境变量的方式传入，详见[Dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)
> > > 
> > > 
> > > 大佬你好，我运行你的命令行企图启动qsign服务，但是报错 ![image](https://user-images.githubusercontent.com/87311200/274635894-fb3e23f8-0659-43bf-8cb2-ca015bb328b7.png) 找不到解决思路，外部有java
> > 
> > 
> > 外部java与docker容器里完全没有关系，你检查下docker里面的java是否正常。
> 
> 然而问题是容器报这个错，会是restarting状态，我无法进去检查里面的java情况，而且我们用的同一命令，为啥我会出现这个问题呢

检查你的Host OS和docker engine版本，可能你系统比较老或者docker太老，镜像的底包很新，host os和docker engine版本太低了跑不起来的，而且报错就是报这个

**Comment by lllrj** [comment]
> > > > > @aohanhongzhi android_id可以从你的device.json获取，传入方式例如：`docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63`，是给container传环境变量的方式传入，详见[Dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)
> > > > 
> > > > 
> > > > 大佬你好，我运行你的命令行企图启动qsign服务，但是报错 ![image](https://user-images.githubusercontent.com/87311200/274635894-fb3e23f8-0659-43bf-8cb2-ca015bb328b7.png) 找不到解决思路，外部有java
> > > 
> > > 
> > > 外部java与docker容器里完全没有关系，你检查下docker里面的java是否正常。
> > 
> > 
> > 然而问题是容器报这个错，会是restarting状态，我无法进去检查里面的java情况，而且我们用的同一命令，为啥我会出现这个问题呢
> 
> 检查你的Host OS和docker engine版本，可能你系统比较老或者docker太老，镜像的底包很新，host os和docker engine版本太低了跑不起来的，而且报错就是报这个

我是阿里云服务器跑的，linux os应该是centos 7.9
![image](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/87311200/741d1bd5-bd26-4847-88a7-399c99894eaf)
docker engine 是19.03.9
这个版本很老吗

**Comment by XZhouQD** [comment]
> > > > > > @aohanhongzhi android_id可以从你的device.json获取，传入方式例如：`docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID={android_id} xzhouqd/qsign:8.9.63`，是给container传环境变量的方式传入，详见[Dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)
> > > > > 
> > > > > 
> > > > > 大佬你好，我运行你的命令行企图启动qsign服务，但是报错 ![image](https://user-images.githubusercontent.com/87311200/274635894-fb3e23f8-0659-43bf-8cb2-ca015bb328b7.png) 找不到解决思路，外部有java
> > > > 
> > > > 
> > > > 外部java与docker容器里完全没有关系，你检查下docker里面的java是否正常。
> > > 
> > > 
> > > 然而问题是容器报这个错，会是restarting状态，我无法进去检查里面的java情况，而且我们用的同一命令，为啥我会出现这个问题呢
> > 
> > 
> > 检查你的Host OS和docker engine版本，可能你系统比较老或者docker太老，镜像的底包很新，host os和docker engine版本太低了跑不起来的，而且报错就是报这个
> 
> 我是阿里云服务器跑的，linux os应该是centos 7.9 ![image](https://user-images.githubusercontent.com/87311200/274794334-741d1bd5-bd26-4847-88a7-399c99894eaf.png) docker engine 是19.03.9 这个版本很老吗

centos 7 确实是太老了，所以能换一下还是换一下吧
