### ISSUE TITLE
使用xzhouqd/qsign:core-1.1.6 release v1.1.6 给go-cqhttp登录报错

### ISSUE THREAD

**Issue by leecoooo** [XZhouQD/unidbg-fetch-qsign#6]
报错如下：
[WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

构建容器命令如下：docker run -d --restart=always --name qsign -p 8890:8080 -e BASE_PATH=/srv/qsign/qsign/txlib/8.9.63 xzhouqd/qsign:core-1.1.6

**Comment by leecoooo** [comment]
用了action里面的版本，出现：[WARNING]: 注册QQ实例时出现错误: Wrong API key. server: http://192.168.1.5:8890/

**Comment by a1046700338** [comment]
我也是这个报错欸

**Comment by Mengzx88** [comment]
+1

**Comment by a1046700338** [comment]
我的报错也是
```
WARNING获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'
WARNING登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45
WARNING你的账号被限制登录, 请配置 SignServer 后重试
```
我的配置文件是这样的
gocqhttp的config文件
```
# ...
  sign-server: 'http://127.0.0.1:8666'
  is-below-110: false
  key: '114514'
```
txlib/8.9.63/config
```json
{
  "server": {
    "host": "0.0.0.0",
    "port": 8666
  },
  "key": "114514",
  "auto_register": true,
  "reload_interval": 40,
  "protocol": {
    "qua": "V1_AND_SQ_8.9.63_4194_YYB_D",
    "version": "8.9.63",
    "code": "4194"
  },
  "unidbg": {
    "dynarmic": false,
    "unicorn": true,
    "debug": false
  }
}
```

**Comment by XZhouQD** [comment]
@leecoooo wrong api key这个似乎是key配置问题？go-cqhttp dev版配置文件里的key配对了吗。（另外我这里主要解决docker化跑不跑得起来的问题而不是gocq怎么连）。

@a1046700338 T544 sign这个，还是先检查下你的qsign启动，看下容器log，因为你是自己mount了配置文件进去，1.1.6的话，配置文件里的reload_interval得删掉不然启动不起来，见[fuqiuluo/unidbg-fetch-qsign/issues/149]，因为我也是自己mount进去的然后被坑了一手（大悲）

**Comment by leecoooo** [comment]
> @leecoooo wrong api key这个似乎是key配置问题？go-cqhttp dev版配置文件里的key配对了吗。（另外我这里主要解决docker化跑不跑得起来的问题而不是gocq怎么连）。
> 
> @a1046700338 T544 sign这个，还是先检查下你的qsign启动，看下容器log，因为你是自己mount了配置文件进去，1.1.6的话，配置文件里的reload_interval得删掉不然启动不起来，见[[fuqiuluo/issues/149](https://github.com/fuqiuluo/unidbg-fetch-qsign/issues/149)]，因为我也是自己mount进去的然后被坑了一手（大悲）

确实是配置问题，用了旧版的配置，用dev重新生成了，这个问题解决了出现了新的问题（挠头

[WARNING]: 注册QQ实例时出现错误: Get "http://192.168.1.5:8890/register?uin=xxxxxx&android_id=xxxxxx&guid=xxxxxx&qimei36=xxxxxx&key=114514": context deadline exceeded (Client.Timeout exceeded while awaiting headers) server: http://192.168.1.5:8890/

[WARNING]: 获取sso sign时出现错误: Post "http://192.168.1.5:8890/sign": context deadline exceeded (Client.Timeout exceeded while awaiting headers) server: http://192.168.1.5:8890/

虽然出错了，但是登录完全没问题。。。

**Comment by XZhouQD** [comment]
到这儿是设备性能问题了，注册那里设备性能低点就要10秒以上，gocq默认超时只有5秒，，，

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mengzx88** [comment]
> 

怎么改 大佬

**Comment by XZhouQD** [comment]
这我实在记不清了，我已经好久没用gocq了，应该是类似于http.timeout之类的配置项吧，可以去gocq那边问问看

**Comment by XZhouQD** [comment]
close due to inactivity
