### ISSUE TITLE
这是哪的问题呀

### ISSUE THREAD

**Issue by Mengzx88** [XZhouQD/unidbg-fetch-qsign#7]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
![QQ截图20230720211824](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/27806444/d00aa1e8-5149-4c8d-9b6b-92efb186a99a)

**Comment by XZhouQD** [comment]
搭配qsign core-1.1.1及以上使用时，go-cqhttp不能使用不含注册的release v1.1.0版本了，得去actions下dev构建版，新的register api（qsign core 1.1.1+）版本gocq还没正式发版哦。如果想继续使用go-cqhttp release v1.1.0，得用xzhouqd/qsign:8.9.63这个tag的image，这是qsign 1.1.0的。启动方式参见[dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)描述里的8.9.63 tag部分

**Comment by Mengzx88** [comment]
> 搭配qsign core-1.1.1及以上使用时，go-cqhttp不能使用不含注册的release v1.1.0版本了，得去actions下dev构建版，新的register api（qsign core 1.1.1+）版本gocq还没正式发版哦。如果想继续使用go-cqhttp release v1.1.0，得用xzhouqd/qsign:8.9.63这个tag的image，这是qsign 1.1.0的。启动方式参见[dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)描述里的8.9.63 tag部分
![QQ截图20230720234803](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/27806444/39b85678-5245-4d23-b9cd-5a5edd6a0946)
![QQ截图20230720234839](https://github.com/XZhouQD/unidbg-fetch-qsign/assets/27806444/47ebc68a-689a-4e68-afe9-ee2442d30993)


我用dev那个注册不了 大佬 再看看

**Comment by XZhouQD** [comment]
> > 搭配qsign core-1.1.1及以上使用时，go-cqhttp不能使用不含注册的release v1.1.0版本了，得去actions下dev构建版，新的register api（qsign core 1.1.1+）版本gocq还没正式发版哦。如果想继续使用go-cqhttp release v1.1.0，得用xzhouqd/qsign:8.9.63这个tag的image，这是qsign 1.1.0的。启动方式参见[dockerhub:xzhouqd/qsign](https://hub.docker.com/r/xzhouqd/qsign)描述里的8.9.63 tag部分
> > ![QQ截图20230720234803](https://user-images.githubusercontent.com/27806444/254937946-39b85678-5245-4d23-b9cd-5a5edd6a0946.png)
> > ![QQ截图20230720234839](https://user-images.githubusercontent.com/27806444/254937964-47ebc68a-689a-4e68-afe9-ee2442d30993.png)
> 
> 我用dev那个注册不了 大佬 再看看

wrong api key，你的gocq配置的签名服务器那里，key填对了吗，然后，机器性能不佳的话，注册api可能需要10秒以上，gocq默认的5秒超时可能不够

**Comment by XZhouQD** [comment]
Close due to inactivity
