### ISSUE TITLE
每次登录成功后过2天左右就会被风控不能发送群消息

### ISSUE THREAD

**Issue by TheTychoStar** [XZhouQD/unidbg-fetch-qsign#8]
（Disscussion链接点进去是404也找不到板块在哪只好发在issue了，请谅解）

用的是Miao-Yunzai，QQ登录后一切正常，但是每次都是大概2天左右，就会被风控，无法发送群消息（私聊可以）。
删除device token以后重新登录验证设备后，一切恢复正常，但大约2天后又出现同样的问题。
不清楚这个是什么引起的，看错误日志也看不出来啥名堂。请教如何解决？

- 错误日志就只有这个：
`[ERRO] ApiRejection { code: -70, message: '群消息发送失败，可能被风控' }`

**Comment by XZhouQD** [comment]
额，sign api是救不了风控的……还是会有因为消息频繁啊之类导致的风控出现的

**Comment by TheTychoStar** [comment]
> 额，sign api是救不了风控的……还是会有因为消息频繁啊之类导致的风控出现的

明白了，能确认不是我没配置对就行。看来要换QQ号了，谢谢。
