### ISSUE TITLE
docker拉取时提示manifest not found

### ISSUE THREAD

**Issue by Pyrokine** [XZhouQD/unidbg-fetch-qsign#9]
Unable to find image 'xzhouqd/qsign:8.9.63' locally
Trying to pull repository docker.io/xzhouqd/qsign ... 
/usr/bin/docker-current: manifest for docker.io/xzhouqd/qsign:8.9.63 not found.
See '/usr/bin/docker-current run --help'.

**Comment by XZhouQD** [comment]
这个我属实理解不了……tag和image在的啊，除非你是特殊架构？image目前只有linux/amd64和linux/arm64，如果你是s390x之类的，那可能不行……

**Comment by Pyrokine** [comment]
> 这个我属实理解不了……tag和image在的啊，除非你是特殊架构？image目前只有linux/amd64和linux/arm64，如果你是s390x之类的，那可能不行……

试了其他tag和latest都不行，用的是腾讯云的centos7，应该是amd64吧

**Comment by XZhouQD** [comment]
latest肯定不行，因为我没有打latest这个tag的，centos我不好说，之前有出过centos因为软件源太老，docker太老导致JAVA_HOME环境变量报错的，但是不应该出现完全拉不到镜像的情况，不妨`uname -a`看一下内核版本和架构？

**Comment by Pyrokine** [comment]
> latest肯定不行，因为我没有打latest这个tag的，centos我不好说，之前有出过centos因为软件源太老，docker太老导致JAVA_HOME环境变量报错的，但是不应该出现完全拉不到镜像的情况，不妨`uname -a`看一下内核版本和架构？

Linux VM-4-9-centos 4.14.129-bbrplus #1 SMP Tue Jun 25 12:23:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by XZhouQD** [comment]
是amd64，那我也无法理解了……确认下到docker hub网络通吗，其他的我也没啥想得出来的了，手动pull也试下，我没头绪了

**Comment by Pyrokine** [comment]
> 

拉了一下其他的库没问题

**Comment by Xuwznln** [comment]
遇到同样的问题了，也是腾讯云的机器，Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
docker pull xzhouqd/qsign:core-1.1.7
Trying to pull repository docker.io/xzhouqd/qsign ... 
manifest for docker.io/xzhouqd/qsign:core-1.1.7 not found
```

```
docker pull xzhouqd/qsign:8.9.63
Trying to pull repository docker.io/xzhouqd/qsign ... 
manifest for docker.io/xzhouqd/qsign:8.9.63 not found
```

**Comment by XZhouQD** [comment]
我唯一能看出来的共同点，大概是你们都是centos？我试着用我腾讯云的机器去pull，ubuntu的机器，没有问题，难道是centos全责？

**Comment by Xuwznln** [comment]
现在docker都基于docker v2，因此需要先升级centos上默认的docker版本，参考https://cloud.tencent.com/developer/article/2170575 教程升级docker到主版本号为24，如果使用宝塔，则升级后重新安装docker管理器，然后再pull即可，实测成功

**Comment by Pyrokine** [comment]
升级docker之后可以正常拉取了，但是会出现JAVA_HOME的问题

**Comment by XZhouQD** [comment]
JAVA_HOME还是系统和docker版本离容器底包过远的问题……8963底包是debian:latest，更高版本底包是eclipse/temurin:11，基于ubuntu 22.04，都是特别新的，只能是升系统或者继续升docker看看啦

**Comment by XZhouQD** [comment]
closed due to inactivity
